ContactList:
  base_url: "https://thinking-tester-contact-list.herokuapp.com"
  token: "Bearer {{token}}"
  endpoints:
    add_contact: "/contacts"
    add_user: "/users"
    get_contact_list: "/contacts"
    get_contact: "/contacts/"
    get_user_profile: "/users/me"
    patch_contact: "/contacts/"
    patch_user: "/users/me"
    login_user: "/users/login"
    logout_user: "/users/logout"
    delete_contact: "/contacts/"
    delete_user: "/users/me"
  contact1:
    first_name: "Carlos"
    last_name: "González"
    birthdate: "1985-07-12"
    email: "carlos.gonzalez@real.com"
    phone: "555123456"
    street1: "Av. de la Constitución 45"
    street2: "Piso 3B"
    city: "Madrid"
    stateProvince: "Madrid"
    postalCode: "28001"
    country: "ES"
  contact2:
    first_name: "Aiko"
    last_name: "Takahashi"
    birthdate: "1992-03-27"
    email: "aiko.takahashi@real.com"
    phone: "09012345678"
    street1: "1 Chome-2-3 Shibuya"
    street2: "Apt 502"
    city: "Tokyo"
    stateProvince: "Tokyo"
    postalCode: "150-0002"
    country: "JP"
  contact3:
    first_name: "Liam"
    last_name: "O'Connor"
    birthdate: "1985-06-15"
    email: "liam.oconnor@real.com"
    phone: "+353871234567"
    street1: "5 Greenway"
    street2: ""
    city: "Dublin"
    stateProvince: ""
    postalCode: "D02 YX88"
    country: "IE"
  contact4:
    first_name: "Akira"
    last_name: "Tanaka"
    birthdate: "1992-03-10"
    email: "akira.tanaka@real.com"
    phone: "+819012345678"
    street1: "3-2-1 Shibuya"
    street2: "Apartment 12F"
    city: "Tokyo"
    stateProvince: "Tokyo"
    postalCode: "150-0001"
    country: "JP"
  contact5:
    first_name: "Carlos"
    last_name: "Rodriguez"
    birthdate: "1978-09-25"
    email: "carlos.rodriguez@real.com"
    phone: "+34911222333"
    street1: "Calle Mayor 10"
    street2: "Piso 3B"
    city: "Madrid"
    stateProvince: "Madrid"
    postalCode: "28013"
    country: "ES"


Mocky:
  base_url: "https://run.mocky.io/v3/"
  token: None
  endpoints:
    get: "af807fa9-43a6-419f-a51e-962fe409a7b8"
    post: "fdb59946-d736-422d-9afd-a914f7fd42d8"
    update: "15d96d11-5e31-4e87-a1cc-64f6771f6960"


