ContactList:
  base_url: "https://thinking-tester-contact-list.herokuapp.com"
  token: "Bearer {{token}}"
  endpoints:
    add_contact: "/contacts"
    add_user: "/users"
    get_contact_list: "/contacts"
    get_contact: "/contacts/"
    get_user_profile: "/users/me"
    patch_contact: "/contacts/"
    patch_user: "/users/me"
    login_user: "/users/login"
    logout_user: "/users/logout"
    delete_contact: "/contacts/"
    delete_user: "/users/me"
  first_user:
    # token: "Bearer {{token}}"
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2FjOTdiZjM5ZTY5MzAwMTNkNTIyODkiLCJpYXQiOjE3NDA0MDQwOTF9.ToP9gYagECY3mT2rAFaxsmzoDZvzVUhTVfN6jzSpLLk"
    first_name: "Izabela"
    last_name: "MonteMniam"
    email: "iza@facts.com"
    password: "sha1sha2"
    id: "67ac97bf39e6930013d52289"
  contact1:
    first_name: "Janusz"
    last_name: "Korwin-Mikke"
    birthdate: "1970-01-01"
    email: "korwin@real.com"
    phone: "123456789"
    street1: "1 Main St."
    street2: "Apartment A"
    city: "Anytown"
    stateProvince: "KS"
    postalCode: "6-66"
    country: "PL"
  contact2:
    first_name: "Anna"
    last_name: "Midlove"
    birthdate: "1950-11-05"
    email: "anna.love.hate@real.com"
    phone: "987654321"
    "street1": "1 Bottom Sq."
    street2: "Apartment Z"
    city: "Anyville"
    stateProvince: "XX"
    postalCode: "44-44"
    country: "RUS"    

Mocky:
  base_url: "https://run.mocky.io/v3/"
  token: None
  endpoints:
    get: "af807fa9-43a6-419f-a51e-962fe409a7b8"
    post: "fdb59946-d736-422d-9afd-a914f7fd42d8"
    update: "15d96d11-5e31-4e87-a1cc-64f6771f6960"


