# GitHub Actions workflow to test a Python REST API project with Pytest and Ruff

name: pytest-rest-api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: List files in the repository
      run: |
        ls -la ${{ github.workspace }}

    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install Ruff
      run: python -m pip install ruff

    # check code quality
    - name: Lint code with Ruff
      run: ruff check --output-format=github --target-version=py312

    - name: Check code formatting with Ruff
      run: ruff format --diff --target-version=py312
      continue-on-error: true

    - name: Create junit directory
      run: mkdir -p junit

    # Run tests, generate coverage and JUnit report
    - name: Test with pytest
      run: |
        pytest tests.py --doctest-modules \
                        --junitxml=junit/test-results.xml \
                        --cov=com --cov-report=xml --cov-report=html

    # Upload pytest test results as an artifact, even if tests fail
    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: junit/test-results.xml
      if: ${{ always() }}
